import { MaterialCommunityIcons } from '@expo/vector-icons';
import { SportType } from '../types/activity';

export const sportTypeToIcon: Record<SportType, keyof typeof MaterialCommunityIcons.glyphMap> = {
  Run: 'run',
  Ride: 'bike',
  Swim: 'swim',
  Walk: 'walk',
  Hike: 'hiking',
  WeightTraining: 'weight-lifter',
  Workout: 'weight-lifter',
  Yoga: 'yoga',
  AlpineSki: 'ski',
  BackcountrySki: 'ski',
  Badminton: 'tennis',
  Canoeing: 'sail-boat',
  Crossfit: 'weight-lifter',
  EBikeRide: 'bike',
  Elliptical: 'ellipse',
  EMountainBikeRide: 'bike',
  Golf: 'golf',
  GravelRide: 'bike',
  Handcycle: 'bike',
  HighIntensityIntervalTraining: 'weight-lifter',
  Kayaking: 'sail-boat',
  MountainBikeRide: 'bike',
  NordicSki: 'ski',
  Pickleball: 'tennis',
  Pilates: 'yoga',
  Racquetball: 'tennis',
  IceSkate: 'skate',
  InlineSkate: 'skate',
  Kitesurf: 'kitesurfing',
  RockClimbing: 'wall',
  RollerSki: 'ski',
  Rowing: 'rowing',
  Sail: 'sail-boat',
  Skateboard: 'skateboard',
  Snowboard: 'snowboard',
  Snowshoe: 'snowflake',
  Soccer: 'soccer',
  Squash: 'tennis',
  StairStepper: 'stairs',
  StandUpPaddling: 'tennis',
  Surfing: 'waves',
  TableTennis: 'tennis',
  Tennis: 'tennis',
  TrailRun: 'run',
  Velomobile: 'bike',
  VirtualRide: 'bike',
  VirtualRow: 'rowing',
  VirtualRun: 'run',
  Wheelchair: 'wheelchair-accessibility',
  Windsurf: 'waves',
};
